# teeth_constants.py

TEETH_LIST = [
    {"tooth_code": "11", "tooth_name": "Upper Right Central Incisor"},
    {"tooth_code": "12", "tooth_name": "Upper Right Lateral Incisor"},
    {"tooth_code": "13", "tooth_name": "Upper Right Canine"},
    {"tooth_code": "14", "tooth_name": "Upper Right First Premolar"},
    {"tooth_code": "15", "tooth_name": "Upper Right Second Premolar"},
    {"tooth_code": "16", "tooth_name": "Upper Right First Molar"},
    {"tooth_code": "17", "tooth_name": "Upper Right Second Molar"},
    {"tooth_code": "18", "tooth_name": "Upper Right Third Molar"},
    {"tooth_code": "21", "tooth_name": "Upper Left Central Incisor"},
    {"tooth_code": "22", "tooth_name": "Upper Left Lateral Incisor"},
    {"tooth_code": "23", "tooth_name": "Upper Left Canine"},
    {"tooth_code": "24", "tooth_name": "Upper Left First Premolar"},
    {"tooth_code": "25", "tooth_name": "Upper Left Second Premolar"},
    {"tooth_code": "26", "tooth_name": "Upper Left First Molar"},
    {"tooth_code": "27", "tooth_name": "Upper Left Second Molar"},
    {"tooth_code": "28", "tooth_name": "Upper Left Third Molar"},
    {"tooth_code": "31", "tooth_name": "Lower Left Central Incisor"},
    {"tooth_code": "32", "tooth_name": "Lower Left Lateral Incisor"},
    {"tooth_code": "33", "tooth_name": "Lower Left Canine"},
    {"tooth_code": "34", "tooth_name": "Lower Left First Premolar"},
    {"tooth_code": "35", "tooth_name": "Lower Left Second Premolar"},
    {"tooth_code": "36", "tooth_name": "Lower Left First Molar"},
    {"tooth_code": "37", "tooth_name": "Lower Left Second Molar"},
    {"tooth_code": "38", "tooth_name": "Lower Left Third Molar"},
    {"tooth_code": "41", "tooth_name": "Lower Right Central Incisor"},
    {"tooth_code": "42", "tooth_name": "Lower Right Lateral Incisor"},
    {"tooth_code": "43", "tooth_name": "Lower Right Canine"},
    {"tooth_code": "44", "tooth_name": "Lower Right First Premolar"},
    {"tooth_code": "45", "tooth_name": "Lower Right Second Premolar"},
    {"tooth_code": "46", "tooth_name": "Lower Right First Molar"},
    {"tooth_code": "47", "tooth_name": "Lower Right Second Molar"},
    {"tooth_code": "48", "tooth_name": "Lower Right Third Molar"},
]
